server:
  port: 9999
  servlet:
    contextPath: /sub
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: lead_exchange
    emailQueue: email_queue
    mobileQueue: mobile_queue
    emailRoutingKey: email_routingkey
    mobileRoutingKey: mobile_routingkey

logging:
  level:
    com.tej.ex.subscriber: TRACE

